sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= "db/#{Rails.env}.sqlite3" %>

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DATABASE_NAME") { ['curiosity', Rails.env].join('_') } %>
  host:     <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  password: <%= ENV.fetch("DATABASE_PASS") { '' } %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port:     <%= ENV.fetch("DATABASE_PORT") { '3306' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'root' } %>

development:
  <<: *mysql

test:
  <<: *mysql

production:
  <<: *mysql
