name: Curiosity Workflow
on: [push]
jobs:
  standard-rb:
    name: Standartize Ruby code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4
      - run: bundle exec standardrb
  ruby-tests:
    name: Run Rake tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4
      - run: bundle exec rake test
