name: Curiosity Workflow
on: [push]
jobs:
  standard-rb:
    name: Standartize Ruby code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4
      - run: bundle exec standardrb
  prettier-js:
    name: Standartize JavaScript code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: bundle-use-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            bundle-use-yarn-
      - run: yarn install
      - run: yarn prettier --write app/javascript/**/*.js
